#!/bin/bash

function install-dev-dependencies() {
  apt-get install -y build-essential automake autoconf libtool 
  apt-get install -y liblog4cpp5-dev libcppunit-dev libjson0-dev libboost-date-time-dev libboost-regex-dev libboost-program-options-dev libboost-math-dev
  apt-get install -y python python-dev python-setuptools
  apt-get install -y libgeos-dev libblas-dev liblapack-dev gfortran
  apt-get install -y git wget
}

function install-bo-lib() {
  wget https://github.com/wuan/bo-lib/archive/v1.3.0.tar.gz
  tar xzf v1.3.0.tar.gz
  cd bo-lib-1.3.0
  ./bootstrap
  ./configure
  make
  tests/test-lib
  make install
  cd ..
  rm -rf bo-lib-1.3.0
}

install-dev-dependencies
install-bo-lib
